### ISSUE TITLE
i have a one question about 'require'

### ISSUE THREAD

**Issue by kmu1205** [ConquestArrow/BP_Obfuscator#1]
hi,
I'm trying to use UnrealJS as a TypeScript. I am writing this because you provided ts file for UClass. However, the file error 'cannot find the name 'Requie' is rising from 'boostrap.ts.' How should we solve this?

here is code

export default function (filename : string)
{
  Context.RunFile('aliases.js')
  
  require('devrequire')(filename) //Compile Error is occur
}

**Comment by ConquestArrow** [comment]
Hello.
Normally, the definition of the `require` function is defined at the beginning of `_part_0_ue.d.ts`.

```typescript
declare global {
	function require(name: string): any;
}
```

Since this definition is global, it is valid from any code.

The following reason may be considered that your error that definition is not found appears.

1. Definition files are not output
2. There are definition files, but the definition of the `require` function has been erased
3. The tsc compiler has not found definition files

In case of 1, please check whether the definition files are in the `typings` directory. If there are no definition files, please try to generate definition files with reference to [this page](https://github.com/ncsoft/Unreal.js/wiki/Autocompletion).

In case of 2 open the `_part_0 _ue.d.ts` file and check it. If the definition of `require` is missing or corrupted, try regenerating the definition files in the same way as above.

In case of 3, check the version of tsc compiler. If the tsc compiler version is 2 or later, the definition file in the `typings` directory will be found automatically. It is unnecessary to specify referrence path. Conversely, in the case of the old tsc version you need to refer to the definition file in your code in the referrence pass.

```ts
/// <reference path="typings/ue.d.ts">/>
```

If you check the above three methods, if not, please tell me about your environment (UnrealEngine, tsc, Unreal.js plugin version) and details of the error. If possible, you can tell me the code that caused your error, I can give you more appropriate advice.

**Comment by kmu1205** [comment]
i change the code

declare **namespace** global {
	function require(name: string): any;
}

require problem is solved, but other problem occur.

here is my code

![image](https://user-images.githubusercontent.com/16569957/45610895-8725d900-ba98-11e8-9584-f177889f1bca.png)


the new problem is when i play javascript in Editor.

in javascript console, 
"Error : ReferenceError : exports is not defined"
"Error: at ...MyTypeScript.js:3:23"
"Error: at ...MyTypeScript.js:40:3

**Comment by kmu1205** [comment]
if i add code

![image](https://user-images.githubusercontent.com/16569957/45612841-441b3400-ba9f-11e8-8f41-c27cfe694b16.png)


Error is occur
"Cannot Find the name module"

**Comment by kmu1205** [comment]
I think 'Export' error is caused by this code.

`import UClass from "uclass"`

**Comment by ConquestArrow** [comment]
> "Error : ReferenceError : exports is not defined"

Oh, I understood the cause.
This problem is caused by TypeScript trans-pile.

It seems that the following code has been output since TypeScript ver.2.3.x, but this code causes an error in Unreal.js.

```js
Object.defineProperty(exports, "__esModule", { value: true });
```
The above code is output if `module:"commonjs"` is specified in `tsconfig.json`. Previous tsc did not output this code.

https://github.com/Microsoft/TypeScript/issues/15795

The problem is that the `exports` object exists in Node.js but not in Unreal.js. Therefore, converted JavaScript code becomes code which causes error in Unreal.js.

Unfortunately, you will have to solve it in one of the following troublesome ways.


1. Delete the `module` configuration line from` tsconfig.json` and replace `import X from "Y"` with `const X = require ("Y")`
2. Delete `Object.defineProperty(exports,"__esModule", {value: true});` from the translated JavaScript file

In the method of 1., you can do it only with tsc, but there is a disadvantage that type information is lost.
Since it is hard to erase the method in 2., it is a good idea to build a build system so that it can be automatically deleted with Gulp and others.

**Comment by ConquestArrow** [comment]
> i change the code
> 
> declare **namespace** global {
> function require(name: string): any;
> }

I think that this definition is incorrect. I think you don't need to change to the definition of namespace.

If you define `declare namespace global {function require ...`, it will be the definition of the object `global.require()`, but it's not a global definition of `require()`.

To add or extend global object definitions, you can use the `declare global {....` notation in TypeScript (　[Global augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) ).

----
> 'cannot find the name 'Requie'
> "Cannot Find the name module"

Another thing I remembered is that it is likely to cause these errors.
Have you installed the type definition (`@types/node`) of Node.js?

`require()` and `module` are APIs Unreal.js added by mimicking Node.js independently. Since these are not pure JavaScript APIs, we also need to add these type definitions. You can substitute in the type definition of Node.js.

Please also check this.

```cmd
npm i @types/node -D
```

**Comment by kmu1205** [comment]
- Delete

 the module configuration line fromtsconfig.json and replace import X from "Y" with const X = require ("Y")

**Comment by kmu1205** [comment]
- [ ] **Delete the module configuration line fromtsconfig.json and replace import X from "Y" with const X = require ("Y")**

if i code that,
A Compile Error occur.
**"Build: Untyped function calls may not accept type arrguments"**

thank you for your Answer.

i'm sure that i installed typescript compile.

![default](https://user-images.githubusercontent.com/16569957/45729033-a5f5ae00-bc05-11e8-8592-14248d952574.png)

**Comment by ConquestArrow** [comment]
> * [ ]  **Delete the module configuration line fromtsconfig.json and replace import X from "Y" with const X = require ("Y")**
> 
> if i code that,
> A Compile Error occur.
> **"Build: Untyped function calls may not accept type arrguments"**

Oh, sorry. I forgot that I needed to add the code.

If you convert an `import` statement into a` const` statement, type information will be lost from `UClass()`. Please change to the following code to regain type information.

1. Update `uclass.d.ts` [latest](https://github.com/ConquestArrow/BP_Obfuscator/commit/3d9f691fb11eccd4109609252569f8a88087ea30)
2. Add the following statement to the beginning of the code
  - `import {UClassified} from "./typings/uclass"`
3. Rewrite the usage of `UClass()` as follows
```ts
	//var w_C = UClass<Class, MyUMG>()(global, MyUMG)  //old code
	var w_C:UClassified<Class,MyUMG> = UClass()(global, MyUMG) //new code
```

**Comment by kmu1205** [comment]
![image2018-9-21_10-30-8](https://user-images.githubusercontent.com/16569957/45855103-82f40700-bd89-11e8-8951-876c59b86700.png)

this is TestWidget which parents of MyUMG(MyUMG is TypeScript)
here is a entire code.

![image](https://user-images.githubusercontent.com/16569957/45855276-4d9be900-bd8a-11e8-84ea-20b635013e18.png)


My Problem is if i call AddToViewport(); 
i can't see Widget's Button and ProgressBar.
And,
if i call console.log(w.Button_38);
The Answer is 'undefined'

 I tried to get this button to be designed in the parents' widget, 
and then to be able to access TypeScript to functionally implement it. 

how can i do that?

I always appreciate your kindness. 
have a nice day.
